/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package carhire.view;

/**
 *
 * @author UDARA DHANUSHKA
 */
public class CarCategory extends javax.swing.JPanel {

    /**
     * Creates new form CarCategory
     */
    public CarCategory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BasePanel2 = new javax.swing.JPanel();
        headerLabel2 = new javax.swing.JLabel();
        formPanel2 = new javax.swing.JPanel();
        carCatIdLabel = new javax.swing.JLabel();
        carCatIdText = new javax.swing.JTextField();
        carNameLabel = new javax.swing.JLabel();
        carNameText = new javax.swing.JTextField();
        submitCategoryButton = new javax.swing.JButton();
        custDataLabel2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        itemDataLabel2 = new javax.swing.JLabel();

        headerLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        headerLabel2.setText("   Car Category");

        carCatIdLabel.setText("Car Category ID");

        carNameLabel.setText("Car Name");

        submitCategoryButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        submitCategoryButton.setText("Submit");
        submitCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitCategoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formPanel2Layout = new javax.swing.GroupLayout(formPanel2);
        formPanel2.setLayout(formPanel2Layout);
        formPanel2Layout.setHorizontalGroup(
            formPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanel2Layout.createSequentialGroup()
                .addGroup(formPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanel2Layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(submitCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemDataLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addGroup(formPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(formPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(formPanel2Layout.createSequentialGroup()
                                .addComponent(carCatIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carCatIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(formPanel2Layout.createSequentialGroup()
                                .addComponent(carNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(formPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formPanel2Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(custDataLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(formPanel2Layout.createSequentialGroup()
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        formPanel2Layout.setVerticalGroup(
            formPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(formPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(formPanel2Layout.createSequentialGroup()
                        .addComponent(custDataLabel2)
                        .addGap(8, 8, 8)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formPanel2Layout.createSequentialGroup()
                        .addGroup(formPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(carCatIdLabel)
                            .addComponent(carCatIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(formPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(carNameLabel)
                            .addComponent(carNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(formPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(itemDataLabel2))
                    .addGroup(formPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(submitCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BasePanel2Layout = new javax.swing.GroupLayout(BasePanel2);
        BasePanel2.setLayout(BasePanel2Layout);
        BasePanel2Layout.setHorizontalGroup(
            BasePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasePanel2Layout.createSequentialGroup()
                .addGroup(BasePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(headerLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                    .addComponent(formPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        BasePanel2Layout.setVerticalGroup(
            BasePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BasePanel2Layout.createSequentialGroup()
                .addComponent(headerLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BasePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BasePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitCategoryButtonActionPerformed
        submitCategory();
    }//GEN-LAST:event_submitCategoryButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BasePanel;
    private javax.swing.JPanel BasePanel1;
    private javax.swing.JPanel BasePanel2;
    private javax.swing.JButton addItemButton;
    private javax.swing.JButton addItemButton1;
    private javax.swing.JLabel carCatIdLabel;
    private javax.swing.JTextField carCatIdText;
    private javax.swing.JLabel carNameLabel;
    private javax.swing.JTextField carNameText;
    private javax.swing.JLabel custDataLabel;
    private javax.swing.JLabel custDataLabel1;
    private javax.swing.JLabel custDataLabel2;
    private javax.swing.JTextField customerIdText;
    private javax.swing.JTextField customerIdText1;
    private javax.swing.JLabel customerLabel;
    private javax.swing.JLabel customerLabel1;
    private javax.swing.JLabel discountLabel;
    private javax.swing.JLabel discountLabel1;
    private javax.swing.JTextField discountText;
    private javax.swing.JTextField discountText1;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel formPanel1;
    private javax.swing.JPanel formPanel2;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel headerLabel1;
    private javax.swing.JLabel headerLabel2;
    private javax.swing.JLabel itemDataLabel;
    private javax.swing.JLabel itemDataLabel1;
    private javax.swing.JLabel itemDataLabel2;
    private javax.swing.JLabel itemIdLabel;
    private javax.swing.JLabel itemIdLabel1;
    private javax.swing.JTextField itemIdText;
    private javax.swing.JTextField itemIdText1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel orderIdLabel;
    private javax.swing.JLabel orderIdLabel1;
    private javax.swing.JTextField orderIdText;
    private javax.swing.JTextField orderIdText1;
    private javax.swing.JLabel qtyLabel;
    private javax.swing.JLabel qtyLabel1;
    private javax.swing.JTextField qtyText;
    private javax.swing.JTextField qtyText1;
    private javax.swing.JButton searchCustomerButton;
    private javax.swing.JButton searchCustomerButton1;
    private javax.swing.JButton searchItemrButton1;
    private javax.swing.JButton searchItemrButton2;
    private javax.swing.JButton submitCategoryButton;
    // End of variables declaration//GEN-END:variables

    private void submitCategory() {
    
    }
}
